language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t douglaszickuhr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true douglaszickuhr/docker-react npm run test
